# Generated by Django 2.0.6 on 2019-03-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='weathermap_id',
            new_name='weathermapId',
        ),
    ]
